version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:lts
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: pwa command used to show the current directory use pwd -L to present the full path from ./root
                command: pwd
            - restore_cache:
                keys:
                    - npm-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install application dependencies
                command: npm install
            - save_cache:
                key: npm-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # - run:
            #     name: Linting
            #     command: npm run lint
            # - run:
            #     name: Testing
            #     command: npm run test --prod
            # - run:
            #     name: Building
            - checkout
            #     command: npm run build:ssr
    deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:lts
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Install angular cli github pages
                command: sudo npm install -g angular-cli-ghpages
            - run:
                name: Install angular cli
                command: sudo npm install -g @angular/cli@7.3.9
            - run:
                name: Building
                command: npm run build deploy
            - run:
                name: Deploy Master to Github pages
                command: ngh dir "./dist/browser" --token "$GITHUB_TOKEN"

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master