version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:lts
        steps:
            - checkout
            - run: echo ${CIRCLE_BRANCH}
            - run: pwd
            - restore_cache:
                keys:
                    - npm-dependencies-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                key: npm-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
    deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:lts
        steps:
            - checkout
            - run: echo ${CIRCLE_BRANCH}
            - restore_cache:
                keys:
                    - npm-dependencies-{{ checksum "package.json" }}
            - run: sudo npm install -g angular-cli-ghpages
            - run: sudo npm install -g @angular/cli
            - run: sudo npm install @angular-devkit/build-angular
            - run: npm run deploy
            - run: ngh dir "./dist/browser" --token "$GITHUB_TOKEN"

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master